name: Auto-Async

on:
  push:
  schedule:
    #自动同步：每天早上1点
    - cron:  0 17 * * *
  watch:
    types: [started]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        env:
          PAT_SYNC: ${{ secrets.PAT_SYNC }}
        run: |
          git config --global user.name 'laosan-xx'
          git config --global user.email 'xxhy1989@gmail.com'
          git pull --unshallow
          git remote add upstream https://github.com/Openwrt-Passwall/openwrt-passwall.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main

          # 使用 PAT 替换远程地址，这样可以更新 workflow 文件
          git remote set-url origin https://x-access-token:${PAT_SYNC}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main
